# Generated by Django 3.2 on 2021-04-08 16:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('title', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('length', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=250)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_sources', to='main_app.country')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CountryMentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.article')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='articles',
            field=models.ManyToManyField(related_name='article_countries', through='main_app.CountryMentions', to='main_app.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='countries',
            field=models.ManyToManyField(related_name='country_articles', through='main_app.CountryMentions', to='main_app.Country'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_articles', to='main_app.source'),
        ),
    ]
